const imagesInstance = {
  person: require("./person.png"),
  clients: require("./newclients.png"),
  iconTiktok: require("./icon-tiktok.png"),
  iconInsta: require("./icon-instagram.png"),
  iconFace: require("./icon-face.png"),
  iconChart: require("./icon-chart.jpg"),
  iconMember: require("./icon-member.jpg"),
  iconIncreate: require("./icon-increat.png"),
  bgDesign: require('./bgDesign.png'),
  asset1:  require('./assets01.png'),
  asset2:  require('./assets02.png'),
  asset3:  require('./assets03.png'),
  asset4:  require('./assets04.png'),
  asset5:  require('./assets05.png'),
  asset6:  require('./assets06.png'),
  banner1: require('./banner01.png'),
  banner2: require('./banner02.png'),
  service: require('./service.jpg'),
  related: require('./related.jpg'),
  aboutme: require('./MARKETING-01.jpg'),
  review1: require("./review5.jpg"),
  review2: require("./review6.jpg"),
  review3: require("./review3.jpg"),
  logoNgang: require("./logo-ngang.png"),
  logoDoc: require("./logo-doc.png"),
  logo: require("./logo-tienlong.png"),
  review4: require("./review4.jpg"),
  salekitbanner: require("./salekit.png"),
  salekit1: require("./1.png"),
  salekit2: require("./2.png"),
  salekit3: require("./3.png"),
  salekit4: require("./4.png"),
};

export default imagesInstance;
